/*compliant code*/
SELECT 1; DELETE FROM temp1; COMMIT; SELECT 2; 
SELECT 1; DELETE FROM temp1; COMMIT; SELECT 2; 
/*violating code*/
SELECT 1; DELETE FROM temp1; SELECT 2;
SELECT 1; DELETE FROM temp1; SELECT 2;
COMMIT; DELETE FROM temp1;
COMMIT; DELETE FROM temp1;
