package org.sonar.plugins.sql.models.msissues;
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.15 at 01:54:13 PM EEST 
//



import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Problem" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Rule" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ProblemDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SourceFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Line" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "problem"
})
@XmlRootElement(name = "Problems")
public class MsIssues {

    @XmlElement(name = "Problem", required = true)
    protected List<MsIssues.Problem> problem;

    /**
     * Gets the value of the problem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the problem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProblem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MsIssues.Problem }
     * 
     * 
     */
    public List<MsIssues.Problem> getProblem() {
        if (problem == null) {
            problem = new ArrayList<MsIssues.Problem>();
        }
        return this.problem;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Rule" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ProblemDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SourceFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Line" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Column" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Severity" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rule",
        "problemDescription",
        "sourceFile",
        "line",
        "column",
        "severity"
    })
    public static class Problem {

        @XmlElement(name = "Rule", required = true)
        protected String rule;
        @XmlElement(name = "ProblemDescription", required = true)
        protected String problemDescription;
        @XmlElement(name = "SourceFile", required = true)
        protected String sourceFile;
        @XmlElement(name = "Line")
        protected int line;
        @XmlElement(name = "Column")
        protected int column;
        @XmlElement(name = "Severity", required = true)
        protected String severity;

        /**
         * Gets the value of the rule property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRule() {
            return rule;
        }

        /**
         * Sets the value of the rule property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRule(String value) {
            this.rule = value;
        }

        /**
         * Gets the value of the problemDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProblemDescription() {
            return problemDescription;
        }

        /**
         * Sets the value of the problemDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProblemDescription(String value) {
            this.problemDescription = value;
        }

        /**
         * Gets the value of the sourceFile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceFile() {
            return sourceFile;
        }

        /**
         * Sets the value of the sourceFile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceFile(String value) {
            this.sourceFile = value;
        }

        /**
         * Gets the value of the line property.
         * 
         */
        public int getLine() {
            return line;
        }

        /**
         * Sets the value of the line property.
         * 
         */
        public void setLine(int value) {
            this.line = value;
        }

        /**
         * Gets the value of the column property.
         * 
         */
        public int getColumn() {
            return column;
        }

        /**
         * Sets the value of the column property.
         * 
         */
        public void setColumn(int value) {
            this.column = value;
        }

        /**
         * Gets the value of the severity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeverity() {
            return severity;
        }

        /**
         * Sets the value of the severity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeverity(String value) {
            this.severity = value;
        }

    }

}
