package org.sonar.plugins.sql.models.cgissues;

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 

// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.15 at 02:02:12 PM EEST 
//

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="file" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="issue" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="severity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="fullname" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "file" })
@XmlRootElement(name = "root")
public class CodeGuardIssues {

	@XmlElement(required = true)
	protected List<CodeGuardIssues.File> file;

	/**
	 * Gets the value of the file property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the file property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFile().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link CodeGuardIssues.File
	 * }
	 * 
	 * 
	 */
	public List<CodeGuardIssues.File> getFile() {
		if (file == null) {
			file = new ArrayList<CodeGuardIssues.File>();
		}
		return this.file;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="issue" maxOccurs="unbounded">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *                 &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *                 &lt;attribute name="severity" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *       &lt;attribute name="fullname" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "issue" })
	public static class File {

		@XmlElement(required = true)
		protected List<CodeGuardIssues.File.Issue> issue;
		@XmlAttribute(name = "fullname")
		protected String fullname;
		@XmlAttribute(name = "name")
		protected String name;

		/**
		 * Gets the value of the issue property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the issue property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getIssue().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link CodeGuardIssues.File.Issue }
		 * 
		 * 
		 */
		public List<CodeGuardIssues.File.Issue> getIssue() {
			if (issue == null) {
				issue = new ArrayList<CodeGuardIssues.File.Issue>();
			}
			return this.issue;
		}

		/**
		 * Gets the value of the fullname property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getFullname() {
			return fullname;
		}

		/**
		 * Sets the value of the fullname property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setFullname(String value) {
			this.fullname = value;
		}

		/**
		 * Gets the value of the name property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getName() {
			return name;
		}

		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setName(String value) {
			this.name = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="column" type="{http://www.w3.org/2001/XMLSchema}int" />
		 *       &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *       &lt;attribute name="severity" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Issue {

			@XmlAttribute(name = "code")
			protected String code;
			@XmlAttribute(name = "line")
			protected Integer line;
			@XmlAttribute(name = "column")
			protected Integer column;
			@XmlAttribute(name = "text")
			protected String text;
			@XmlAttribute(name = "message")
			protected String message;
			@XmlAttribute(name = "severity")
			protected String severity;

			/**
			 * Gets the value of the code property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getCode() {
				return code;
			}

			/**
			 * Sets the value of the code property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setCode(String value) {
				this.code = value;
			}

			/**
			 * Gets the value of the line property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getLine() {
				return line;
			}

			/**
			 * Sets the value of the line property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setLine(Integer value) {
				this.line = value;
			}

			/**
			 * Gets the value of the column property.
			 * 
			 * @return possible object is {@link Integer }
			 * 
			 */
			public Integer getColumn() {
				return column;
			}

			/**
			 * Sets the value of the column property.
			 * 
			 * @param value
			 *            allowed object is {@link Integer }
			 * 
			 */
			public void setColumn(Integer value) {
				this.column = value;
			}

			/**
			 * Gets the value of the text property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getText() {
				return text;
			}

			/**
			 * Sets the value of the text property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setText(String value) {
				this.text = value;
			}

			/**
			 * Gets the value of the message property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getMessage() {
				return message;
			}

			/**
			 * Sets the value of the message property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setMessage(String value) {
				this.message = value;
			}

			/**
			 * Gets the value of the severity property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getSeverity() {
				return severity;
			}

			/**
			 * Sets the value of the severity property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setSeverity(String value) {
				this.severity = value;
			}

		}

	}

}
