//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.15 at 09:03:12 PM EEST 
//


package org.opencover;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Summary"/>
 *         &lt;element ref="{}MetadataToken"/>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}FileRef"/>
 *         &lt;element ref="{}SequencePoints"/>
 *       &lt;/sequence>
 *       &lt;attribute name="visited" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cyclomaticComplexity" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="sequenceCoverage" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="branchCoverage" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="isConstructor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isStatic" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isGetter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isSetter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "summary",
    "metadataToken",
    "name",
    "fileRef",
    "sequencePoints"
})
@XmlRootElement(name = "Method")
public class Method {

    @XmlElement(name = "Summary", required = true)
    protected Summary summary;
    @XmlElement(name = "MetadataToken")
    protected int metadataToken;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "FileRef", required = true)
    protected FileRef fileRef;
    @XmlElement(name = "SequencePoints", required = true)
    protected SequencePoints sequencePoints;
    @XmlAttribute(name = "visited")
    protected String visited;
    @XmlAttribute(name = "cyclomaticComplexity")
    protected Integer cyclomaticComplexity;
    @XmlAttribute(name = "sequenceCoverage")
    protected Integer sequenceCoverage;
    @XmlAttribute(name = "branchCoverage")
    protected Integer branchCoverage;
    @XmlAttribute(name = "isConstructor")
    protected String isConstructor;
    @XmlAttribute(name = "isStatic")
    protected String isStatic;
    @XmlAttribute(name = "isGetter")
    protected String isGetter;
    @XmlAttribute(name = "isSetter")
    protected String isSetter;

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link Summary }
     *     
     */
    public Summary getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summary }
     *     
     */
    public void setSummary(Summary value) {
        this.summary = value;
    }

    /**
     * Gets the value of the metadataToken property.
     * 
     */
    public int getMetadataToken() {
        return metadataToken;
    }

    /**
     * Sets the value of the metadataToken property.
     * 
     */
    public void setMetadataToken(int value) {
        this.metadataToken = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the fileRef property.
     * 
     * @return
     *     possible object is
     *     {@link FileRef }
     *     
     */
    public FileRef getFileRef() {
        return fileRef;
    }

    /**
     * Sets the value of the fileRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileRef }
     *     
     */
    public void setFileRef(FileRef value) {
        this.fileRef = value;
    }

    /**
     * Gets the value of the sequencePoints property.
     * 
     * @return
     *     possible object is
     *     {@link SequencePoints }
     *     
     */
    public SequencePoints getSequencePoints() {
        return sequencePoints;
    }

    /**
     * Sets the value of the sequencePoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link SequencePoints }
     *     
     */
    public void setSequencePoints(SequencePoints value) {
        this.sequencePoints = value;
    }

    /**
     * Gets the value of the visited property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisited() {
        return visited;
    }

    /**
     * Sets the value of the visited property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisited(String value) {
        this.visited = value;
    }

    /**
     * Gets the value of the cyclomaticComplexity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCyclomaticComplexity() {
        return cyclomaticComplexity;
    }

    /**
     * Sets the value of the cyclomaticComplexity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCyclomaticComplexity(Integer value) {
        this.cyclomaticComplexity = value;
    }

    /**
     * Gets the value of the sequenceCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSequenceCoverage() {
        return sequenceCoverage;
    }

    /**
     * Sets the value of the sequenceCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSequenceCoverage(Integer value) {
        this.sequenceCoverage = value;
    }

    /**
     * Gets the value of the branchCoverage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBranchCoverage() {
        return branchCoverage;
    }

    /**
     * Sets the value of the branchCoverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBranchCoverage(Integer value) {
        this.branchCoverage = value;
    }

    /**
     * Gets the value of the isConstructor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsConstructor() {
        return isConstructor;
    }

    /**
     * Sets the value of the isConstructor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsConstructor(String value) {
        this.isConstructor = value;
    }

    /**
     * Gets the value of the isStatic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsStatic() {
        return isStatic;
    }

    /**
     * Sets the value of the isStatic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsStatic(String value) {
        this.isStatic = value;
    }

    /**
     * Gets the value of the isGetter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsGetter() {
        return isGetter;
    }

    /**
     * Sets the value of the isGetter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsGetter(String value) {
        this.isGetter = value;
    }

    /**
     * Gets the value of the isSetter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsSetter() {
        return isSetter;
    }

    /**
     * Sets the value of the isSetter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSetter(String value) {
        this.isSetter = value;
    }

}
